name: toming
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4559613
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Tom Ming Chen '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B5A490'
    - '#78644C'
    - '#160C03'
    - '#4B2815'
    - '#FFFFFA'
  brandStrength: 0.2883995
  lightness: 1
  saturation: 0.509667
  rhythmicContrast: 0.5
purpose: []
