title: 'Thom Ming Chen '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.509667
  brandStrength: 0.3034371
  lightness: 1
  brandColors:
    - '#282727'
    - '#5D5452'
    - '#B3A5A3'
    - '#D8CDC7'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: toming
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5332975
layout_spectrum: 1
