name: toming
favicon: null
layout_spectrum: 0.6457868404686451
typography_spectrum: 0.6287005390040576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ae2729'
    - '#afacad'
    - '#67625b'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
