name: toming
favicon: null
layout_spectrum: 0.6457868404686451
typography_spectrum: 0.6287005390040576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b3335'
    - '#dfd4ca'
    - '#bcbac0'
    - '#655d61'
    - '#837977'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
